<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:cli="http://clientes.tcc.com.co/">
   <soap:Header/>
   <soap:Body>
      <cli:GrabarDespacho4>
         <!--Optional:-->
         <cli:objDespacho>
            <!--Optional:-->
            <clave>MEDPLASTICOSOJARA</clave>
            <!--Optional:-->
            <codigolote></codigolote>
            <!--Optional:-->
            <fechahoralote>2016-05-13</fechahoralote>
            <!--Optional:-->
            <numeroremesa></numeroremesa>
            <!--Optional:-->
            <numeroDepacho></numeroDepacho>
            <!--Optional:-->
            <unidadnegocio>1</unidadnegocio>
            <!--Optional:-->
            <fechadespacho>2016-05-16</fechadespacho>
            <!--Optional:-->
            <cuentaremitente>1575600</cuentaremitente>
            <!--Optional:-->
            <sederemitente>81279</sederemitente>
            <!--Optional:-->
            <primernombreremitente>ojara</primernombreremitente>
            <!--Optional:-->
            <segundonombreremitente></segundonombreremitente>
            <!--Optional:-->
            <primerapellidoremitente></primerapellidoremitente>
            <!--Optional:-->
            <segundoapellidoremitente></segundoapellidoremitente>
            <!--Optional:-->
            <razonsocialremitente>ojaar</razonsocialremitente>
            <!--Optional:-->
            <naturalezaremitente>J</naturalezaremitente>
            <!--Optional:-->
            <tipoidentificacionremitente>NIT</tipoidentificacionremitente>
            <!--Optional:-->
            <identificacionremitente>890920025</identificacionremitente>
            <!--Optional:-->
            <telefonoremitente>1234567</telefonoremitente>
            <!--Optional:-->
            <direccionremitente>CRA 1 N 362N</direccionremitente>
            <!--Optional:-->
            <ciudadorigen>05001000</ciudadorigen>
            <!--Optional:-->
            <tipoidentificaciondestinatario>CC</tipoidentificaciondestinatario>
            <!--Optional:-->
            <identificaciondestinatario></identificaciondestinatario>
            <!--Optional:-->
            <sededestinatario></sededestinatario>
            <!--Optional:-->
            <primernombredestinatario>DESTINATARIO</primernombredestinatario>
            <!--Optional:-->
            <segundonombredestinatario>PRUEBAS</segundonombredestinatario>
            <!--Optional:-->
            <primerapellidodestinatario>SERVICIO</primerapellidodestinatario>
            <!--Optional:-->
            <segundoapellidodestinatario>WEB</segundoapellidodestinatario>
            <!--Optional:-->
            <razonsocialdestinatario></razonsocialdestinatario>
            <!--Optional:-->
            <naturalezadestinatario>N</naturalezadestinatario>
            <!--Optional:-->
            <direcciondestinatario>CALLE 35C N° 20-40 JORDAN - PARAISO</direcciondestinatario>
            <!--Optional:-->
            <telefonodestinatario>3012861375</telefonodestinatario>
            <!--Optional:-->
            <ciudaddestinatario>76001000</ciudaddestinatario>
            <!--Optional:-->
            <barriodestinatario></barriodestinatario>
            <!--Optional:-->
            <totalpeso>50</totalpeso>
            <!--Optional:-->
            <totalpesovolumen>140</totalpesovolumen>
            <!--Optional:-->
            <formapago></formapago>
            <!--Optional:-->
            <observaciones>ESTO ES UNA PRUEBA DE DESPACHO POR SERVICIO WEB</observaciones>
            <!--Optional:-->
            <llevabodega></llevabodega>
            <!--Optional:-->
            <recogebodega></recogebodega>
            <!--Optional:-->
            <centrocostos></centrocostos>
            <!--Optional:-->
            <totalvalorproducto></totalvalorproducto>
            <!--Zero or more repetitions:-->
            <unidad>
               <tipounidad>TIPO_UND_PAQ</tipounidad>
               <tipoempaque>A</tipoempaque>
               <claseempaque>CLEM_CAJA</claseempaque>
               <dicecontener>PRUEBAS</dicecontener>
               <!--Optional:-->
               <cantidadunidades>1</cantidadunidades>
               <kilosreales>10</kilosreales>
               <largo>0</largo>
               <alto>0</alto>
               <ancho>0</ancho>
               <pesovolumen>30</pesovolumen>
               <valormercancia>525000</valormercancia>
               <codigobarras>123456780</codigobarras>
               <numerobolsa>3</numerobolsa>
               <referencias></referencias>
            </unidad>
            <unidad>
               <tipounidad>TIPO_UND_PAQ</tipounidad>
               <tipoempaque>B</tipoempaque>
               <claseempaque>CLEM_CAJA</claseempaque>
               <dicecontener>PRUEBAS</dicecontener>
               <!--Optional:-->
               <cantidadunidades>1</cantidadunidades>
               <kilosreales>10</kilosreales>
               <largo>0</largo>
               <alto>0</alto>
               <ancho>0</ancho>
               <pesovolumen>30</pesovolumen>
               <valormercancia>525000</valormercancia>
               <codigobarras>123456780</codigobarras>
               <numerobolsa>3</numerobolsa>
               <referencias></referencias>
            </unidad>
            <unidad>
               <tipounidad>TIPO_UND_DOCD</tipounidad>
               <tipoempaque></tipoempaque>
               <claseempaque>CLEM_SOBRE</claseempaque>
               <dicecontener>PRUEBAS</dicecontener>
               <!--Optional:-->
               <cantidadunidades>1</cantidadunidades>
               <kilosreales>0</kilosreales>
               <largo>0</largo>
               <alto>0</alto>
               <ancho>0</ancho>
               <pesovolumen>0</pesovolumen>
               <valormercancia>2000</valormercancia>
               <codigobarras>123456780</codigobarras>
               <numerobolsa></numerobolsa>
               <referencias></referencias>
            </unidad>
            <!--Zero or more repetitions:-->
            <documentoreferencia>
               <tipodocumento>FA</tipodocumento>
               <numerodocumento>EAM003</numerodocumento>
               <fechadocumento>2016-01-07</fechadocumento>
            </documentoreferencia>
            <numeroReferenciaCliente></numeroReferenciaCliente>
            <!--Optional:-->
            <fuente></fuente>
            <generarDocumentos>true</generarDocumentos>
         </cli:objDespacho>
         <!--Optional:-->
         <cli:remesa>0</cli:remesa>
         <cli:respuesta>0</cli:respuesta>
         <!--Optional:-->
         <cli:mensaje>0</cli:mensaje>
      </cli:GrabarDespacho4>
   </soap:Body>
</soap:Envelope>
