//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 08:35:23 PM ECT 
//


package com.yaesta.integration.vitex.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stockKeepingUnitIdFrom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stockKeepingUnitIdTo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stockKeepingUnitIdFrom",
    "stockKeepingUnitIdTo"
})
@XmlRootElement(name = "ImageServiceCopyAllImagesFromSkuToSku")
public class ImageServiceCopyAllImagesFromSkuToSku {

    protected Integer stockKeepingUnitIdFrom;
    protected Integer stockKeepingUnitIdTo;

    /**
     * Gets the value of the stockKeepingUnitIdFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStockKeepingUnitIdFrom() {
        return stockKeepingUnitIdFrom;
    }

    /**
     * Sets the value of the stockKeepingUnitIdFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStockKeepingUnitIdFrom(Integer value) {
        this.stockKeepingUnitIdFrom = value;
    }

    /**
     * Gets the value of the stockKeepingUnitIdTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStockKeepingUnitIdTo() {
        return stockKeepingUnitIdTo;
    }

    /**
     * Sets the value of the stockKeepingUnitIdTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStockKeepingUnitIdTo(Integer value) {
        this.stockKeepingUnitIdTo = value;
    }

}
