
package co.com.tcc.clientes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InformacionRemesas", targetNamespace = "http://clientes.tcc.com.co/", wsdlLocation = "http://clientes.tcc.com.co/servicios/informacionremesas.asmx?wsdl")
public class InformacionRemesas
    extends Service
{

    private final static URL INFORMACIONREMESAS_WSDL_LOCATION;
    private final static WebServiceException INFORMACIONREMESAS_EXCEPTION;
    private final static QName INFORMACIONREMESAS_QNAME = new QName("http://clientes.tcc.com.co/", "InformacionRemesas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://clientes.tcc.com.co/servicios/informacionremesas.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFORMACIONREMESAS_WSDL_LOCATION = url;
        INFORMACIONREMESAS_EXCEPTION = e;
    }

    public InformacionRemesas() {
        super(__getWsdlLocation(), INFORMACIONREMESAS_QNAME);
    }

    public InformacionRemesas(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFORMACIONREMESAS_QNAME, features);
    }

    public InformacionRemesas(URL wsdlLocation) {
        super(wsdlLocation, INFORMACIONREMESAS_QNAME);
    }

    public InformacionRemesas(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFORMACIONREMESAS_QNAME, features);
    }

    public InformacionRemesas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InformacionRemesas(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InformacionRemesasSoap
     */
    @WebEndpoint(name = "InformacionRemesasSoap")
    public InformacionRemesasSoap getInformacionRemesasSoap() {
        return super.getPort(new QName("http://clientes.tcc.com.co/", "InformacionRemesasSoap"), InformacionRemesasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformacionRemesasSoap
     */
    @WebEndpoint(name = "InformacionRemesasSoap")
    public InformacionRemesasSoap getInformacionRemesasSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clientes.tcc.com.co/", "InformacionRemesasSoap"), InformacionRemesasSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFORMACIONREMESAS_EXCEPTION!= null) {
            throw INFORMACIONREMESAS_EXCEPTION;
        }
        return INFORMACIONREMESAS_WSDL_LOCATION;
    }

}
