
package co.com.tcc.clientes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsDespachos", targetNamespace = "http://clientes.tcc.com.co/", wsdlLocation = "http://clientes.tcc.com.co/servicios/wsdespachos.asmx?wsdl")
public class WsDespachos
    extends Service
{

    private final static URL WSDESPACHOS_WSDL_LOCATION;
    private final static WebServiceException WSDESPACHOS_EXCEPTION;
    private final static QName WSDESPACHOS_QNAME = new QName("http://clientes.tcc.com.co/", "wsDespachos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://clientes.tcc.com.co/servicios/wsdespachos.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDESPACHOS_WSDL_LOCATION = url;
        WSDESPACHOS_EXCEPTION = e;
    }

    public WsDespachos() {
        super(__getWsdlLocation(), WSDESPACHOS_QNAME);
    }

    public WsDespachos(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDESPACHOS_QNAME, features);
    }

    public WsDespachos(URL wsdlLocation) {
        super(wsdlLocation, WSDESPACHOS_QNAME);
    }

    public WsDespachos(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDESPACHOS_QNAME, features);
    }

    public WsDespachos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDespachos(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap")
    public WsDespachosSoap getWsDespachosSoap() {
        return super.getPort(new QName("http://clientes.tcc.com.co/", "wsDespachosSoap"), WsDespachosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap")
    public WsDespachosSoap getWsDespachosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clientes.tcc.com.co/", "wsDespachosSoap"), WsDespachosSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDESPACHOS_EXCEPTION!= null) {
            throw WSDESPACHOS_EXCEPTION;
        }
        return WSDESPACHOS_WSDL_LOCATION;
    }

}
